blank_issues_enabled: true
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Ask general Home Assistant setup questions in the community forum.
