name: HACS

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  validate-hacs:
    name: Validate HACS
    runs-on: ubuntu-latest

    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin
